# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_lists', models.ManyToManyField(related_name='all_items', to='login.User')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_creator', to='login.User')),
            ],
        ),
    ]
